/*
Package gopher contains a single image of the Go gopher. It is included to
guarantee that at least one image is always available for some examples
to run successfully.

This file was automatically generated by go-bindata.
*/
package gopher
